### ISSUE TITLE
Add stress command

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/havener#211]
Add new command called `stress` to start a container that creates arbitrary load on nodes. This can be useful in scenarios to test whether a certain task still works even under harsh conditions.

Example deployment YAML:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: stress

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stress
  namespace: stress
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: stress
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - stress
      containers:
      - name: stress
        image:  progrium/stress
        command:
        - /bin/sh
        - -c
        - stress --cpu 4
```
